// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_ALERT_HANDLER_H_
#define OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_ALERT_HANDLER_H_

#include "sw/device/lib/devicetables/dt_api.h"
#include <stdint.h>

typedef enum {
  kDtAlertHandlerRegBlockCore = 0,
  kDtAlertHandlerRegBlockCount = 1,
} dt_alert_handler_reg_block_t;

typedef enum {
  kDtAlertHandlerIrqTypeClassa = 0,
  kDtAlertHandlerIrqTypeClassb = 1,
  kDtAlertHandlerIrqTypeClassc = 2,
  kDtAlertHandlerIrqTypeClassd = 3,
  kDtAlertHandlerIrqTypeCount = 4,
} dt_alert_handler_irq_type_t;

typedef enum {
  kDtAlertHandlerClockClk = 0,
  kDtAlertHandlerClockEdn = 1,
  kDtAlertHandlerClockCount = 2,
} dt_alert_handler_clock_t;

typedef struct dt_alert_handler {
  dt_device_id_t device_id;
  uint32_t base_addrs[kDtAlertHandlerRegBlockCount];
  uint32_t irqs[kDtAlertHandlerIrqTypeCount];
  dt_clock_t clocks[kDtAlertHandlerClockCount];
} dt_alert_handler_t;

/**
 * Convert a global IRQ ID to a local alert_handler IRQ type.
 *
 * @param dt Pointer to an instance of alert_handler.
 * @param irq A global IRQ ID.
 * @return The local alert_handler IRQ type of this irq.
 *
 * IMPORTANT This function assumes that the global IRQ belongs to the instance
 * of alert_handler passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`
 *
 * FIXME How should we handle errors (when the invariant above is violated)?
 */
static inline dt_alert_handler_irq_type_t dt_alert_handler_irq_type(
    const dt_alert_handler_t *dt,
    dt_irq_t irq) {
  // FIXME Should check that irq >= dt->irqs[0] and irq < dt->irqs[0] + kDtAlertHandlerIrqTypeCount
  return irq - dt->irqs[0];
}

#endif  // OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_ALERT_HANDLER_H_
