// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_FLASH_CTRL_H_
#define OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_FLASH_CTRL_H_

#include "sw/device/lib/devicetables/dt_api.h"
#include <stdint.h>

typedef enum {
  kDtFlashCtrlRegBlockCore = 0,
  kDtFlashCtrlRegBlockPrim = 1,
  kDtFlashCtrlRegBlockMem = 2,
  kDtFlashCtrlRegBlockCount = 3,
} dt_flash_ctrl_reg_block_t;

typedef enum {
  kDtFlashCtrlIrqTypeProgEmpty = 0,
  kDtFlashCtrlIrqTypeProgLvl = 1,
  kDtFlashCtrlIrqTypeRdFull = 2,
  kDtFlashCtrlIrqTypeRdLvl = 3,
  kDtFlashCtrlIrqTypeOpDone = 4,
  kDtFlashCtrlIrqTypeCorrErr = 5,
  kDtFlashCtrlIrqTypeCount = 6,
} dt_flash_ctrl_irq_type_t;

typedef enum {
  kDtFlashCtrlClockClk = 0,
  kDtFlashCtrlClockOtp = 1,
  kDtFlashCtrlClockCount = 2,
} dt_flash_ctrl_clock_t;

typedef enum {
  kDtFlashCtrlPinTck = 0,
  kDtFlashCtrlPinTms = 1,
  kDtFlashCtrlPinTdi = 2,
  kDtFlashCtrlPinTdo = 3,
  kDtFlashCtrlPinCount = 4,
} dt_flash_ctrl_pin_t;

typedef struct dt_flash_ctrl {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtFlashCtrlRegBlockCount];
    dt_irq_t irqs[kDtFlashCtrlIrqTypeCount];
    dt_clock_t clocks[kDtFlashCtrlClockCount];
    dt_pin_t pins[kDtFlashCtrlPinCount];
  } __internal;
} dt_flash_ctrl_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of flash_ctrl.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_flash_ctrl_device_id(
    const dt_flash_ctrl_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of flash_ctrl.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_flash_ctrl_reg_block(
    const dt_flash_ctrl_t *dt,
    dt_flash_ctrl_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

/**
 * Get the global IRQ ID of a local flash_ctrl IRQ type for a given instance.
 *
 * @param dt Pointer to an instance of flash_ctrl.
 * @param irq_type A local flash_ctrl IRQ type.
 * @return A global IRQ ID that corresponds to the local IRQ type of this instance.
 */
static inline dt_irq_t dt_flash_ctrl_irq_id(
    const dt_flash_ctrl_t *dt,
    dt_flash_ctrl_irq_type_t irq_type) {
  return dt->__internal.irqs[irq_type];
}

/**
 * Convert a global IRQ ID to a local flash_ctrl IRQ type.
 *
 * @param dt Pointer to an instance of flash_ctrl.
 * @param irq A global IRQ ID that belongs to this instance.
 * @return The local flash_ctrl IRQ type, or `kDtFlashCtrlIrqTypeCount`.
 *
 * NOTE This function assumes that the global IRQ belongs to the instance
 * of flash_ctrl passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`. Otherwise, this function will return
 * `kDtFlashCtrlIrqTypeCount`.
 */
static inline dt_flash_ctrl_irq_type_t dt_flash_ctrl_irq_type(
    const dt_flash_ctrl_t *dt,
    dt_irq_t irq) {
  dt_flash_ctrl_irq_type_t count = kDtFlashCtrlIrqTypeCount;
  if (irq < dt->__internal.irqs[0] || irq >= dt->__internal.irqs[0] + (dt_irq_t)count) {
    return count;
  }
  return irq - dt->__internal.irqs[0];
}

/**
 * Get the pin description of an instance.
 *
 * @param dt Pointer to an instance of flash_ctrl.
 * @param pin Requested pin.
 * @return Description of the requested pin for this instance.
 */
static inline dt_pin_t dt_flash_ctrl_pin(
    const dt_flash_ctrl_t *dt,
    dt_flash_ctrl_pin_t pin) {
  return dt->__internal.pins[pin];
}
#endif  // OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_FLASH_CTRL_H_
