// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_PWRMGR_H_
#define OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_PWRMGR_H_

#include "sw/device/lib/devicetables/dt_api.h"
#include <stdint.h>

typedef enum {
  kDtPwrmgrRegBlockCore = 0,
  kDtPwrmgrRegBlockCount = 1,
} dt_pwrmgr_reg_block_t;

typedef enum {
  kDtPwrmgrIrqTypeWakeup = 0,
  kDtPwrmgrIrqTypeCount = 1,
} dt_pwrmgr_irq_type_t;

typedef enum {
  kDtPwrmgrClockClk = 0,
  kDtPwrmgrClockSlow = 1,
  kDtPwrmgrClockLc = 2,
  kDtPwrmgrClockEsc = 3,
  kDtPwrmgrClockCount = 4,
} dt_pwrmgr_clock_t;

typedef struct dt_pwrmgr {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtPwrmgrRegBlockCount];
    dt_irq_t irqs[kDtPwrmgrIrqTypeCount];
    dt_clock_t clocks[kDtPwrmgrClockCount];
  } __internal;
} dt_pwrmgr_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of pwrmgr.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_pwrmgr_device_id(
    const dt_pwrmgr_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of pwrmgr.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_pwrmgr_reg_block(
    const dt_pwrmgr_t *dt,
    dt_pwrmgr_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

/**
 * Get the global IRQ ID of a local pwrmgr IRQ type for a given instance.
 *
 * @param dt Pointer to an instance of pwrmgr.
 * @param irq_type A local pwrmgr IRQ type.
 * @return A global IRQ ID that corresponds to the local IRQ type of this instance.
 */
static inline dt_irq_t dt_pwrmgr_irq_id(
    const dt_pwrmgr_t *dt,
    dt_pwrmgr_irq_type_t irq_type) {
  return dt->__internal.irqs[irq_type];
}

/**
 * Convert a global IRQ ID to a local pwrmgr IRQ type.
 *
 * @param dt Pointer to an instance of pwrmgr.
 * @param irq A global IRQ ID that belongs to this instance.
 * @return The local pwrmgr IRQ type, or `kDtPwrmgrIrqTypeCount`.
 *
 * NOTE This function assumes that the global IRQ belongs to the instance
 * of pwrmgr passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`. Otherwise, this function will return
 * `kDtPwrmgrIrqTypeCount`.
 */
static inline dt_pwrmgr_irq_type_t dt_pwrmgr_irq_type(
    const dt_pwrmgr_t *dt,
    dt_irq_t irq) {
  dt_pwrmgr_irq_type_t count = kDtPwrmgrIrqTypeCount;
  if (irq < dt->__internal.irqs[0] || irq >= dt->__internal.irqs[0] + (dt_irq_t)count) {
    return count;
  }
  return irq - dt->__internal.irqs[0];
}

#endif  // OPENTITAN_HW_TOP_EARLGREY_SW_AUTOGEN_DEVICETABLES_DT_PWRMGR_H_
