// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_AON_TIMER_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_AON_TIMER_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtAonTimerRegBlockCore = 0,
  kDtAonTimerRegBlockCount = 1,
} dt_aon_timer_reg_block_t;

typedef enum {
  kDtAonTimerIrqTypeWkupTimerExpired = 0,
  kDtAonTimerIrqTypeWdogTimerBark = 1,
  kDtAonTimerIrqTypeCount = 2,
} dt_aon_timer_irq_type_t;

typedef enum {
  kDtAonTimerClockClk = 0,
  kDtAonTimerClockAon = 1,
  kDtAonTimerClockCount = 2,
} dt_aon_timer_clock_t;

typedef struct dt_aon_timer {
  dt_device_id_t device_id;
  uint32_t base_addrs[kDtAonTimerRegBlockCount];
  uint32_t irqs[kDtAonTimerIrqTypeCount];
  dt_clock_t clocks[kDtAonTimerClockCount];
} dt_aon_timer_t;

/**
 * Convert a global IRQ ID to a local aon_timer IRQ type.
 *
 * @param dt Pointer to an instance of aon_timer.
 * @param irq A global IRQ ID.
 * @return The local aon_timer IRQ type of this irq.
 *
 * IMPORTANT This function assumes that the global IRQ belongs to the instance
 * of aon_timer passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`
 *
 * FIXME How should we handle errors (when the invariant above is violated)?
 */
static inline dt_aon_timer_irq_type_t dt_aon_timer_irq_type(
    const dt_aon_timer_t *dt, dt_irq_t irq) {
  // FIXME Should check that irq >= dt->irqs[0] and irq < dt->irqs[0] +
  // kDtAonTimerIrqTypeCount
  return irq - dt->irqs[0];
}

#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_AON_TIMER_H_
