// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ADC_CTRL_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ADC_CTRL_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtAdcCtrlRegBlockCore = 0,
  kDtAdcCtrlRegBlockCount = 1,
} dt_adc_ctrl_reg_block_t;

typedef enum {
  kDtAdcCtrlIrqTypeMatchPending = 0,
  kDtAdcCtrlIrqTypeCount = 1,
} dt_adc_ctrl_irq_type_t;

typedef enum {
  kDtAdcCtrlClockClk = 0,
  kDtAdcCtrlClockAon = 1,
  kDtAdcCtrlClockCount = 2,
} dt_adc_ctrl_clock_t;

typedef struct dt_adc_ctrl {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtAdcCtrlRegBlockCount];
    dt_irq_t irqs[kDtAdcCtrlIrqTypeCount];
    dt_clock_t clocks[kDtAdcCtrlClockCount];
  } __internal;
} dt_adc_ctrl_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of adc_ctrl.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_adc_ctrl_device_id(const dt_adc_ctrl_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of adc_ctrl.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_adc_ctrl_reg_block(
    const dt_adc_ctrl_t *dt, dt_adc_ctrl_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

/**
 * Get the global IRQ ID of a local adc_ctrl IRQ type for a given instance.
 *
 * @param dt Pointer to an instance of adc_ctrl.
 * @param irq_type A local adc_ctrl IRQ type.
 * @return A global IRQ ID that corresponds to the local IRQ type of this
 * instance.
 */
static inline dt_irq_t dt_adc_ctrl_irq_id(const dt_adc_ctrl_t *dt,
                                          dt_adc_ctrl_irq_type_t irq_type) {
  return dt->__internal.irqs[irq_type];
}

/**
 * Convert a global IRQ ID to a local adc_ctrl IRQ type.
 *
 * @param dt Pointer to an instance of adc_ctrl.
 * @param irq A global IRQ ID that belongs to this instance.
 * @return The local adc_ctrl IRQ type, or `kDtAdcCtrlIrqTypeCount`.
 *
 * NOTE This function assumes that the global IRQ belongs to the instance
 * of adc_ctrl passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`. Otherwise, this function will
 * return `kDtAdcCtrlIrqTypeCount`.
 */
static inline dt_adc_ctrl_irq_type_t dt_adc_ctrl_irq_type(
    const dt_adc_ctrl_t *dt, dt_irq_t irq) {
  dt_adc_ctrl_irq_type_t count = kDtAdcCtrlIrqTypeCount;
  if (irq < dt->__internal.irqs[0] ||
      irq >= dt->__internal.irqs[0] + (dt_irq_t)count) {
    return count;
  }
  return irq - dt->__internal.irqs[0];
}

#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ADC_CTRL_H_
