// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ADC_CTRL_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ADC_CTRL_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtAdcCtrlRegBlockCore = 0,
  kDtAdcCtrlRegBlockCount = 1,
} dt_adc_ctrl_reg_block_t;

typedef enum {
  kDtAdcCtrlIrqTypeMatchPending = 0,
  kDtAdcCtrlIrqTypeCount = 1,
} dt_adc_ctrl_irq_type_t;

typedef enum {
  kDtAdcCtrlClockClk = 0,
  kDtAdcCtrlClockAon = 1,
  kDtAdcCtrlClockCount = 2,
} dt_adc_ctrl_clock_t;

typedef enum {
  kDtAdcCtrlPinctrlInputCount = 0,
  kDtAdcCtrlPinctrlOutputCount = 0,
} dt_adc_ctrl_pinctrl_t;

typedef struct dt_adc_ctrl {
  dt_device_id_t device_id;
  uint32_t base_addrs[kDtAdcCtrlRegBlockCount];
  uint32_t irqs[kDtAdcCtrlIrqTypeCount];
  dt_clock_t clocks[kDtAdcCtrlClockCount];
} dt_adc_ctrl_t;

/**
 * Convert a global IRQ ID to a local adc_ctrl IRQ type.
 *
 * @param dt Pointer to an instance of adc_ctrl.
 * @param irq A global IRQ ID.
 * @return The local adc_ctrl IRQ type of this irq.
 *
 * IMPORTANT This function assumes that the global IRQ belongs to the instance
 * of adc_ctrl passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`
 *
 * FIXME How should we handle errors (when the invariant above is violated)?
 */
static inline dt_adc_ctrl_irq_type_t dt_adc_ctrl_irq_type(
    const dt_adc_ctrl_t *dt, dt_irq_t irq) {
  // FIXME Should check that irq >= dt->irqs[0] and irq < dt->irqs[0] +
  // kDtAdcCtrlIrqTypeCount
  return irq - dt->irqs[0];
}

#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ADC_CTRL_H_
