// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ENTROPY_SRC_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ENTROPY_SRC_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtEntropySrcRegBlockCore = 0,
  kDtEntropySrcRegBlockCount = 1,
} dt_entropy_src_reg_block_t;

typedef enum {
  kDtEntropySrcIrqTypeEsEntropyValid = 0,
  kDtEntropySrcIrqTypeEsHealthTestFailed = 1,
  kDtEntropySrcIrqTypeEsObserveFifoReady = 2,
  kDtEntropySrcIrqTypeEsFatalErr = 3,
  kDtEntropySrcIrqTypeCount = 4,
} dt_entropy_src_irq_type_t;

typedef enum {
  kDtEntropySrcClockClk = 0,
  kDtEntropySrcClockCount = 1,
} dt_entropy_src_clock_t;

typedef struct dt_entropy_src {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtEntropySrcRegBlockCount];
    dt_irq_t irqs[kDtEntropySrcIrqTypeCount];
    dt_clock_t clocks[kDtEntropySrcClockCount];
  } __internal;
} dt_entropy_src_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of entropy_src.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_entropy_src_device_id(
    const dt_entropy_src_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of entropy_src.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_entropy_src_reg_block(
    const dt_entropy_src_t *dt, dt_entropy_src_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

/**
 * Get the global IRQ ID of a local entropy_src IRQ type for a given instance.
 *
 * @param dt Pointer to an instance of entropy_src.
 * @param irq_type A local entropy_src IRQ type.
 * @return A global IRQ ID that corresponds to the local IRQ type of this
 * instance.
 */
static inline dt_irq_t dt_entropy_src_irq_id(
    const dt_entropy_src_t *dt, dt_entropy_src_irq_type_t irq_type) {
  return dt->__internal.irqs[irq_type];
}

/**
 * Convert a global IRQ ID to a local entropy_src IRQ type.
 *
 * @param dt Pointer to an instance of entropy_src.
 * @param irq A global IRQ ID that belongs to this instance.
 * @return The local entropy_src IRQ type, or `kDtEntropySrcIrqTypeCount`.
 *
 * NOTE This function assumes that the global IRQ belongs to the instance
 * of entropy_src passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`. Otherwise, this function will
 * return `kDtEntropySrcIrqTypeCount`.
 */
static inline dt_entropy_src_irq_type_t dt_entropy_src_irq_type(
    const dt_entropy_src_t *dt, dt_irq_t irq) {
  dt_entropy_src_irq_type_t count = kDtEntropySrcIrqTypeCount;
  if (irq < dt->__internal.irqs[0] ||
      irq >= dt->__internal.irqs[0] + (dt_irq_t)count) {
    return count;
  }
  return irq - dt->__internal.irqs[0];
}

#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_ENTROPY_SRC_H_
