// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_OTBN_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_OTBN_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtOtbnRegBlockCore = 0,
  kDtOtbnRegBlockCount = 1,
} dt_otbn_reg_block_t;

typedef enum {
  kDtOtbnIrqTypeDone = 0,
  kDtOtbnIrqTypeCount = 1,
} dt_otbn_irq_type_t;

typedef enum {
  kDtOtbnClockClk = 0,
  kDtOtbnClockEdn = 1,
  kDtOtbnClockOtp = 2,
  kDtOtbnClockCount = 3,
} dt_otbn_clock_t;

typedef struct dt_otbn {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtOtbnRegBlockCount];
    dt_irq_t irqs[kDtOtbnIrqTypeCount];
    dt_clock_t clocks[kDtOtbnClockCount];
  } __internal;
} dt_otbn_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of otbn.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_otbn_device_id(const dt_otbn_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of otbn.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_otbn_reg_block(const dt_otbn_t *dt,
                                         dt_otbn_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

/**
 * Get the global IRQ ID of a local otbn IRQ type for a given instance.
 *
 * @param dt Pointer to an instance of otbn.
 * @param irq_type A local otbn IRQ type.
 * @return A global IRQ ID that corresponds to the local IRQ type of this
 * instance.
 */
static inline dt_irq_t dt_otbn_irq_id(const dt_otbn_t *dt,
                                      dt_otbn_irq_type_t irq_type) {
  return dt->__internal.irqs[irq_type];
}

/**
 * Convert a global IRQ ID to a local otbn IRQ type.
 *
 * @param dt Pointer to an instance of otbn.
 * @param irq A global IRQ ID that belongs to this instance.
 * @return The local otbn IRQ type, or `kDtOtbnIrqTypeCount`.
 *
 * NOTE This function assumes that the global IRQ belongs to the instance
 * of otbn passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`. Otherwise, this function will
 * return `kDtOtbnIrqTypeCount`.
 */
static inline dt_otbn_irq_type_t dt_otbn_irq_type(const dt_otbn_t *dt,
                                                  dt_irq_t irq) {
  dt_otbn_irq_type_t count = kDtOtbnIrqTypeCount;
  if (irq < dt->__internal.irqs[0] ||
      irq >= dt->__internal.irqs[0] + (dt_irq_t)count) {
    return count;
  }
  return irq - dt->__internal.irqs[0];
}

#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_OTBN_H_
