// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_PATTGEN_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_PATTGEN_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtPattgenRegBlockCore = 0,
  kDtPattgenRegBlockCount = 1,
} dt_pattgen_reg_block_t;

typedef enum {
  kDtPattgenIrqTypeDoneCh0 = 0,
  kDtPattgenIrqTypeDoneCh1 = 1,
  kDtPattgenIrqTypeCount = 2,
} dt_pattgen_irq_type_t;

typedef enum {
  kDtPattgenClockClk = 0,
  kDtPattgenClockCount = 1,
} dt_pattgen_clock_t;

typedef enum {
  kDtPattgenPinPda0Tx = 0,
  kDtPattgenPinPcl0Tx = 1,
  kDtPattgenPinPda1Tx = 2,
  kDtPattgenPinPcl1Tx = 3,
  kDtPattgenPinCount = 4,
} dt_pattgen_pin_t;

typedef struct dt_pattgen {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtPattgenRegBlockCount];
    dt_irq_t irqs[kDtPattgenIrqTypeCount];
    dt_clock_t clocks[kDtPattgenClockCount];
    dt_pin_t pins[kDtPattgenPinCount];
  } __internal;
} dt_pattgen_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of pattgen.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_pattgen_device_id(const dt_pattgen_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of pattgen.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_pattgen_reg_block(const dt_pattgen_t *dt,
                                            dt_pattgen_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

/**
 * Get the global IRQ ID of a local pattgen IRQ type for a given instance.
 *
 * @param dt Pointer to an instance of pattgen.
 * @param irq_type A local pattgen IRQ type.
 * @return A global IRQ ID that corresponds to the local IRQ type of this
 * instance.
 */
static inline dt_irq_t dt_pattgen_irq_id(const dt_pattgen_t *dt,
                                         dt_pattgen_irq_type_t irq_type) {
  return dt->__internal.irqs[irq_type];
}

/**
 * Convert a global IRQ ID to a local pattgen IRQ type.
 *
 * @param dt Pointer to an instance of pattgen.
 * @param irq A global IRQ ID that belongs to this instance.
 * @return The local pattgen IRQ type, or `kDtPattgenIrqTypeCount`.
 *
 * NOTE This function assumes that the global IRQ belongs to the instance
 * of pattgen passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`. Otherwise, this function will
 * return `kDtPattgenIrqTypeCount`.
 */
static inline dt_pattgen_irq_type_t dt_pattgen_irq_type(const dt_pattgen_t *dt,
                                                        dt_irq_t irq) {
  dt_pattgen_irq_type_t count = kDtPattgenIrqTypeCount;
  if (irq < dt->__internal.irqs[0] ||
      irq >= dt->__internal.irqs[0] + (dt_irq_t)count) {
    return count;
  }
  return irq - dt->__internal.irqs[0];
}

/**
 * Get the pin description of an instance.
 *
 * @param dt Pointer to an instance of pattgen.
 * @param pin Requested pin.
 * @return Description of the requested pin for this instance.
 */
static inline dt_pin_t dt_pattgen_pin(const dt_pattgen_t *dt,
                                      dt_pattgen_pin_t pin) {
  return dt->__internal.pins[pin];
}
#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_PATTGEN_H_
