// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_RV_TIMER_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_RV_TIMER_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtRvTimerRegBlockCore = 0,
  kDtRvTimerRegBlockCount = 1,
} dt_rv_timer_reg_block_t;

typedef enum {
  kDtRvTimerIrqTypeTimerExpiredHart0Timer0 = 0,
  kDtRvTimerIrqTypeCount = 1,
} dt_rv_timer_irq_type_t;

typedef enum {
  kDtRvTimerClockClk = 0,
  kDtRvTimerClockCount = 1,
} dt_rv_timer_clock_t;

typedef enum {
  kDtRvTimerPinctrlInputCount = 0,
  kDtRvTimerPinctrlOutputCount = 0,
} dt_rv_timer_pinctrl_t;

typedef struct dt_rv_timer {
  dt_device_id_t device_id;
  uint32_t base_addrs[kDtRvTimerRegBlockCount];
  uint32_t irqs[kDtRvTimerIrqTypeCount];
  dt_clock_t clocks[kDtRvTimerClockCount];
} dt_rv_timer_t;

/**
 * Convert a global IRQ ID to a local rv_timer IRQ type.
 *
 * @param dt Pointer to an instance of rv_timer.
 * @param irq A global IRQ ID.
 * @return The local rv_timer IRQ type of this irq.
 *
 * IMPORTANT This function assumes that the global IRQ belongs to the instance
 * of rv_timer passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`
 *
 * FIXME How should we handle errors (when the invariant above is violated)?
 */
static inline dt_rv_timer_irq_type_t dt_rv_timer_irq_type(
    const dt_rv_timer_t *dt, dt_irq_t irq) {
  // FIXME Should check that irq >= dt->irqs[0] and irq < dt->irqs[0] +
  // kDtRvTimerIrqTypeCount
  return irq - dt->irqs[0];
}

#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_RV_TIMER_H_
