// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SYSRST_CTRL_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SYSRST_CTRL_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtSysrstCtrlRegBlockCore = 0,
  kDtSysrstCtrlRegBlockCount = 1,
} dt_sysrst_ctrl_reg_block_t;

typedef enum {
  kDtSysrstCtrlIrqTypeEventDetected = 0,
  kDtSysrstCtrlIrqTypeCount = 1,
} dt_sysrst_ctrl_irq_type_t;

typedef enum {
  kDtSysrstCtrlClockClk = 0,
  kDtSysrstCtrlClockAon = 1,
  kDtSysrstCtrlClockCount = 2,
} dt_sysrst_ctrl_clock_t;

typedef enum {
  kDtSysrstCtrlPinAcPresent = 0,
  kDtSysrstCtrlPinKey0In = 1,
  kDtSysrstCtrlPinKey1In = 2,
  kDtSysrstCtrlPinKey2In = 3,
  kDtSysrstCtrlPinPwrbIn = 4,
  kDtSysrstCtrlPinLidOpen = 5,
  kDtSysrstCtrlPinBatDisable = 6,
  kDtSysrstCtrlPinKey0Out = 7,
  kDtSysrstCtrlPinKey1Out = 8,
  kDtSysrstCtrlPinKey2Out = 9,
  kDtSysrstCtrlPinPwrbOut = 10,
  kDtSysrstCtrlPinZ3Wakeup = 11,
  kDtSysrstCtrlPinEcRstL = 12,
  kDtSysrstCtrlPinFlashWpL = 13,
  kDtSysrstCtrlPinCount = 14,
} dt_sysrst_ctrl_pin_t;

typedef struct dt_sysrst_ctrl {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtSysrstCtrlRegBlockCount];
    dt_irq_t irqs[kDtSysrstCtrlIrqTypeCount];
    dt_clock_t clocks[kDtSysrstCtrlClockCount];
    dt_pin_t pins[kDtSysrstCtrlPinCount];
  } __internal;
} dt_sysrst_ctrl_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of sysrst_ctrl.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_sysrst_ctrl_device_id(
    const dt_sysrst_ctrl_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of sysrst_ctrl.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_sysrst_ctrl_reg_block(
    const dt_sysrst_ctrl_t *dt, dt_sysrst_ctrl_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

/**
 * Get the global IRQ ID of a local sysrst_ctrl IRQ type for a given instance.
 *
 * @param dt Pointer to an instance of sysrst_ctrl.
 * @param irq_type A local sysrst_ctrl IRQ type.
 * @return A global IRQ ID that corresponds to the local IRQ type of this
 * instance.
 */
static inline dt_irq_t dt_sysrst_ctrl_irq_id(
    const dt_sysrst_ctrl_t *dt, dt_sysrst_ctrl_irq_type_t irq_type) {
  return dt->__internal.irqs[irq_type];
}

/**
 * Convert a global IRQ ID to a local sysrst_ctrl IRQ type.
 *
 * @param dt Pointer to an instance of sysrst_ctrl.
 * @param irq A global IRQ ID that belongs to this instance.
 * @return The local sysrst_ctrl IRQ type, or `kDtSysrstCtrlIrqTypeCount`.
 *
 * NOTE This function assumes that the global IRQ belongs to the instance
 * of sysrst_ctrl passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`. Otherwise, this function will
 * return `kDtSysrstCtrlIrqTypeCount`.
 */
static inline dt_sysrst_ctrl_irq_type_t dt_sysrst_ctrl_irq_type(
    const dt_sysrst_ctrl_t *dt, dt_irq_t irq) {
  dt_sysrst_ctrl_irq_type_t count = kDtSysrstCtrlIrqTypeCount;
  if (irq < dt->__internal.irqs[0] ||
      irq >= dt->__internal.irqs[0] + (dt_irq_t)count) {
    return count;
  }
  return irq - dt->__internal.irqs[0];
}

/**
 * Get the pin description of an instance.
 *
 * @param dt Pointer to an instance of sysrst_ctrl.
 * @param pin Requested pin.
 * @return Description of the requested pin for this instance.
 */
static inline dt_pin_t dt_sysrst_ctrl_pin(const dt_sysrst_ctrl_t *dt,
                                          dt_sysrst_ctrl_pin_t pin) {
  return dt->__internal.pins[pin];
}
#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SYSRST_CTRL_H_
