// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SRAM_CTRL_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SRAM_CTRL_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtSramCtrlRegBlockRegs = 0,
  kDtSramCtrlRegBlockRam = 1,
  kDtSramCtrlRegBlockCount = 2,
} dt_sram_ctrl_reg_block_t;

typedef enum {
  kDtSramCtrlClockClk = 0,
  kDtSramCtrlClockOtp = 1,
  kDtSramCtrlClockCount = 2,
} dt_sram_ctrl_clock_t;

typedef enum {
  kDtSramCtrlPinctrlInputCount = 0,
  kDtSramCtrlPinctrlOutputCount = 0,
} dt_sram_ctrl_pinctrl_t;

typedef struct dt_sram_ctrl {
  dt_device_id_t device_id;
  uint32_t base_addrs[kDtSramCtrlRegBlockCount];
  dt_clock_t clocks[kDtSramCtrlClockCount];
} dt_sram_ctrl_t;

#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SRAM_CTRL_H_
