// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SPI_HOST_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SPI_HOST_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtSpiHostRegBlockCore = 0,
  kDtSpiHostRegBlockCount = 1,
} dt_spi_host_reg_block_t;

typedef enum {
  kDtSpiHostIrqTypeError = 0,
  kDtSpiHostIrqTypeSpiEvent = 1,
  kDtSpiHostIrqTypeCount = 2,
} dt_spi_host_irq_type_t;

typedef enum {
  kDtSpiHostClockClk = 0,
  kDtSpiHostClockCount = 1,
} dt_spi_host_clock_t;

typedef enum {
  kDtSpiHostPinSck = 0,
  kDtSpiHostPinCsb = 1,
  kDtSpiHostPinSd0 = 2,
  kDtSpiHostPinSd1 = 3,
  kDtSpiHostPinSd2 = 4,
  kDtSpiHostPinSd3 = 5,
  kDtSpiHostPinCount = 6,
} dt_spi_host_pin_t;

typedef struct dt_spi_host {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtSpiHostRegBlockCount];
    dt_irq_t irqs[kDtSpiHostIrqTypeCount];
    dt_clock_t clocks[kDtSpiHostClockCount];
    dt_pin_t pins[kDtSpiHostPinCount];
  } __internal;
} dt_spi_host_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of spi_host.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_spi_host_device_id(const dt_spi_host_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of spi_host.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_spi_host_reg_block(
    const dt_spi_host_t *dt, dt_spi_host_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

/**
 * Get the global IRQ ID of a local spi_host IRQ type for a given instance.
 *
 * @param dt Pointer to an instance of spi_host.
 * @param irq_type A local spi_host IRQ type.
 * @return A global IRQ ID that corresponds to the local IRQ type of this
 * instance.
 */
static inline dt_irq_t dt_spi_host_irq_id(const dt_spi_host_t *dt,
                                          dt_spi_host_irq_type_t irq_type) {
  return dt->__internal.irqs[irq_type];
}

/**
 * Convert a global IRQ ID to a local spi_host IRQ type.
 *
 * @param dt Pointer to an instance of spi_host.
 * @param irq A global IRQ ID that belongs to this instance.
 * @return The local spi_host IRQ type, or `kDtSpiHostIrqTypeCount`.
 *
 * NOTE This function assumes that the global IRQ belongs to the instance
 * of spi_host passed in parameter. In other words, it must be the case that
 * `dt->device_id == dt_irq_to_device(irq)`. Otherwise, this function will
 * return `kDtSpiHostIrqTypeCount`.
 */
static inline dt_spi_host_irq_type_t dt_spi_host_irq_type(
    const dt_spi_host_t *dt, dt_irq_t irq) {
  dt_spi_host_irq_type_t count = kDtSpiHostIrqTypeCount;
  if (irq < dt->__internal.irqs[0] ||
      irq >= dt->__internal.irqs[0] + (dt_irq_t)count) {
    return count;
  }
  return irq - dt->__internal.irqs[0];
}

/**
 * Get the pin description of an instance.
 *
 * @param dt Pointer to an instance of spi_host.
 * @param pin Requested pin.
 * @return Description of the requested pin for this instance.
 */
static inline dt_pin_t dt_spi_host_pin(const dt_spi_host_t *dt,
                                       dt_spi_host_pin_t pin) {
  return dt->__internal.pins[pin];
}
#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_SPI_HOST_H_
