// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Device table API auto-generated by `reggen`

#ifndef OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_TRIAL1_H_
#define OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_TRIAL1_H_

#include <stdint.h>

#include "sw/device/lib/devicetables/dt_api.h"

typedef enum {
  kDtTrial1RegBlockCore = 0,
  kDtTrial1RegBlockCount = 1,
} dt_trial1_reg_block_t;

typedef enum {
  kDtTrial1ClockFixed = 0,
  kDtTrial1ClockCount = 1,
} dt_trial1_clock_t;

typedef struct dt_trial1 {
  struct {
    dt_device_id_t device_id;
    uint32_t base_addrs[kDtTrial1RegBlockCount];
    dt_clock_t clocks[kDtTrial1ClockCount];
  } __internal;
} dt_trial1_t;

/**
 * Get the device ID of an instance.
 *
 * @param dt Pointer to an instance of trial1.
 * @return The device ID of that instance.
 */
static inline dt_device_id_t dt_trial1_device_id(const dt_trial1_t *dt) {
  return dt->__internal.device_id;
}

/**
 * Get the register base address of an instance.
 *
 * @param dt Pointer to an instance of trial1.
 * @param reg_block The register block requested.
 * @return The register base address of the requested block.
 */
static inline uint32_t dt_trial1_reg_block(const dt_trial1_t *dt,
                                           dt_trial1_reg_block_t reg_block) {
  return dt->__internal.base_addrs[reg_block];
}

#endif  // OPENTITAN_SW_DEVICE_LIB_DEVICETABLES_DT_TRIAL1_H_
