// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// DO NOT EDIT THIS FILE DIRECTLY.
// It has been generated with
// $ ./util/design/gen-lc-state-enc.py --seed 10167336684108184581
//
mod unlock_raw_token;

pub const AllZeroToken = 0x0;
pub const RndCnstRawUnlockToken = 0x1c8be2ff12790ae2e6d6a68151cbd084;
pub const AllZeroTokenHashed = 0x3852305baecf5ff1d5c1d25f6db9058d;
pub const RndCnstRawUnlockTokenHashed = 0xdec8cca47526bc0793af7bb7560dd5a2;
