// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// DO NOT EDIT THIS FILE DIRECTLY.
// It has been generated with
// $ ./util/design/gen-lc-state-enc.py --seed ${lc_st_enc.config['seed']}
//
mod unlock_raw_token;

% for token in lc_st_enc.config['tokens']:
pub const ${token['name']} = ${"0x{:x}".format( token['value'])};
% endfor
